[cli.options]
  stream = false
  payload_path = ""

[deployment.online.parameters]
  model_id = "ibm/granite-3-3-8b-instruct"  # underlying model of WatsonxChat
  url = "https://us-south.ml.cloud.ibm.com"  
  space_id = "b0e2bf7b-3ec7-4390-a79c-e74f2c00401b"

[deployment.software_specification]
  name = "runtime-24.1-py3.11"
  base_sw_spec = "runtime-24.1-py3.11"

[mlflow]
enabled = false           # set true when ready
tracking_uri = "http://your-mlflow-server:5000"
experiment_name = "peds_post_discharge_agent"